### ISSUE TITLE
[BUG] SMTP not working gmail.

### ISSUE THREAD

**Issue by pcf-twitkowski** [blueprintue/blueprintue-self-hosted-edition#47]
## Description
When using gmail smtp with PHPMailer cannot send mail when registering new users or restarting password.

## Steps to reproduce this issue
1.  Provide MAIL configuration according to documentation and use gmail smtp e.g.

MAIL_USE_SMTP: "true"
MAIL_SMTP_HOST: "smtp.gmail.com"
MAIL_SMTP_PORT: "587"
MAIL_USE_SMTP_AUTH: "true"
MAIL_SMTP_USER: "blueprintue@xxx.com"
MAIL_SMTP_PASSWORD: "XXX" <- this is app password from gmail
MAIL_FROM_ADDRESS: "blueprintue@xxx.com"
MAIL_FROM_NAME: "blueprintUE self-hosted edition"
MAIL_CONTACT_TO: "blueprintue@xxx.com"

2. Run docker container
3. Try to register new user

## Expected behavior
This should send registration mail and proceed to next page.

## Actual behavior
Getting error: Error, could not create account (#500)

## Screenshots
![image](https://github.com/blueprintue/blueprintue-self-hosted-edition/assets/138876907/9a9acce6-9349-4b0b-a403-0334b4ca7679)

## Additional context
all 'xxx' are actual correct gmail name for my company

I've fixed it by adding:
$this->mailer->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
 
in https://github.com/blueprintue/blueprintue-self-hosted-edition/blob/main/app/helpers/MailerHelper.php after line 34

I've fixed it for gmail smtp but not sure how it would work with local smtp.

**Comment by rancoud** [comment]
Thank you for your issue.
I have added an option in the environment variables to enable or disable TLS: `MAIL_USE_SMTP_TLS `
