### ISSUE TITLE
[FEATURE] Provide source code to bue-render

### ISSUE THREAD

**Issue by desplesda** [blueprintue/blueprintue-self-hosted-edition#51]
First: thank you very much indeed for open sourcing BlueprintUE! I'm using it for documentation on our library, and being able to show interactive blueprints in our documentation has been absolutely incredible.

## My problem

The bue-render frontend component is minified, which makes modifications and improvements difficult.

## My suggestion

I'd very much like it if the unminified source code to `bue-render/render.js` could be released, so that people can contribute changes.

## Alternatives

If I want to make changes to bue-render, I either need to modify the minified code (which can be challenging), attempt to 'de-minify' the code by replacing variable names, or writing another implementation, which would be a duplication of effort

## Additional context

Once again, thank you for releasing the code that you have!

**Comment by k----n** [comment]
I ran it through a code beautifier: https://gist.github.com/k----n/7b6952c03132f74141498186a1b6ef32

It looks like it might have been compiled by something else.

**Comment by rancoud** [comment]
Hello, for the moment the `bue-render` is not open source.
