### ISSUE TITLE
[QUESTION]  About the LICENSE

### ISSUE THREAD

**Issue by cronofear-dev** [blueprintue/blueprintue-self-hosted-edition#75]
Sorry to bother you about this. I noticed the repo is under a MIT License so I was wondering if I could use the `bue-render` files in this repo (render.js/.css) for other applications on the client side (also under MIT License). 

Again, sorry if this doesn't go here, you're free to close the issue if that's the case. But it would be nice knowing if I can use the files, I'm not too familiar with the License stuff.

**Comment by rancoud** [comment]
If I follow this document https://choosealicense.com/licenses/mit/#suggest-this-license we can see what you can do, do not and conditions.

**Permissions**
* Commercial use
* Distribution
* Modification
* Private use

**Conditions**
* License and copyright notice

**Limitations**
* Liability
* Warranty

Based on that, I will said you can use the `bue-render`, but it will be still locked as minified version.

**Comment by cronofear-dev** [comment]
Thank you for the reply!
I will see what I can do with the non-minified version and if it fits my need, I recently started using the Verse language again and I would like to make a tool for it. Again, thanks for the insights!
