### ISSUE TITLE
[FEATURE] Logfiles/Errors

### ISSUE THREAD

**Issue by Waldehyd** [blueprintue/blueprintue-self-hosted-edition#96]
I used the FTP Method to install, but I am stuck with 
"Error
An error occured, please try later."

I can't seem to find any logfiles on any further information?

**Comment by rancoud** [comment]
Hello, you can see PHP errors using that method in the README.md: https://github.com/blueprintue/blueprintue-self-hosted-edition?tab=readme-ov-file#how-to-show-php-errors

**Comment by Waldehyd** [comment]
I see, adding either of those causes 500 error for me. Worked around it using:

    $file = $rootDir . $ds . '500-' . gmdate("Y-m-d", time()) . '.txt';
    $errorLog = gmdate("Y-m-d H:i:s", time()) . "\t";

    if ($request !== null) {
        $errorLog .= $request->getMethod() . "\t" . $request->getUri();
    } else {
        $errorLog .= "No request available";
    }

    $errorLog .= "\t" . $t->getMessage() . "\n";
    @file_put_contents($file, $errorLog, FILE_APPEND); 


Now i get: 

2024-10-27 11:46:34	No request available	Rancoud\Environment\Environment::convertType(): Argument #1 ($value) must be of type string, float given, called in /var/www/virtual/mikrovr/blueprintsue/vendor/rancoud/environment/src/Environment.php on line 563

**Comment by rancoud** [comment]
In `index.php`at line 26 remove that: `$env->override(Rancoud\Environment\Environment::GETENV_ALL);`

**Comment by Waldehyd** [comment]
That led me to a new Error, and now I'm at a loss

2024-10-27 12:04:31	GET	https://blueprints.virtuos.world/	Error Execute

**Comment by rancoud** [comment]
Did you add a blueprint (you can see it in the database)? if yes I supposed it's because it missing the anonymous user.

**Comment by Waldehyd** [comment]
Went with Docker Compose now, I think it was related to the shared hosting enviroment.
